# Generated by Django 3.1.4 on 2020-12-20 06:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')])),
                ('description', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(2, 'Description must be greater than 2 characters')])),
                ('section', models.CharField(choices=[('child_dress', 'bolalar kiyimlari'), ('man_dress', 'erkaklar kiyimlari'), ('woman_dress', 'ayollar kiyimlari'), ('home', 'uy jihozlari'), ('toys', "o'yinchoqlar"), ('books', 'kitoblar')], max_length=32)),
                ('region', models.CharField(choices=[('Tashkent_city', 'Toshkent shahar'), ('Tashkent', 'Toshkent viloyat'), ('Nukus', 'Nukus'), ('Urgench', 'Urganch'), ('Bukhara', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Termiz', 'Termiz'), ('Qarshi', 'Qarshi'), ('Samarkand', 'Samarqand'), ('Guliston', 'Guliston'), ('Djizzakh', 'Jizzax'), ('Fergana', "Farg'ona"), ('Namangan', 'Namangan'), ('Andijon', 'Andijon')], max_length=32)),
                ('phone_number', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Phone number must be 7 characters')])),
                ('contact_info', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(2, 'Contact info must be greater than 2 characters')])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
