# Generated by Django 3.1.4 on 2020-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
