# Generated by Django 3.1.4 on 2020-12-23 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201223_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7, 'Phone number must be 7 characters')]),
        ),
    ]
