# Generated by Django 3.1.4 on 2020-12-23 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201223_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9, 'Phone number must be 9 characters')]),
        ),
    ]
