# Generated by Django 3.1.4 on 2020-12-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.imagealbum'),
            preserve_default=False,
        ),
    ]
