# Generated by Django 3.1.4 on 2020-12-23 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20201223_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(help_text='Ismingiz', max_length=16),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=126, validators=[django.core.validators.MinLengthValidator(6, "Parol kamida 6 xonali bo'lishi kerak! ")]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.IntegerField(help_text="telefon raqamingiz. 7 ta raqam bo'lishi kerak", unique=True, validators=[django.core.validators.RegexValidator(message='Length has to be 9', regex='^.{9}$')]),
        ),
    ]
